import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./components/NavBar";
import Footer from "./components/Footer";
import { Theme } from "@radix-ui/themes";
import "./theme-config.css";
import "@radix-ui/themes/styles.css";
const poppins = Poppins({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-poppins",
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Daddy Store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={poppins.variable}>
        <NavBar />
        <Theme appearance="light">
          <main className="p-5 min-h-[calc(100vh-132px)] ">{children}</main>
        </Theme>
        <Footer />
      </body>
    </html>
  );
}
